web:
    build: .
    volumes:
        - .:/app
    links:
        - db
    ports:
        - "40000:4000"

mix:
    image: matteosister/mix
    volumes:
        - .:/app
    working_dir: /app

db:
    image: mysql
    environment:
        MYSQL_USER: medicine
        MYSQL_PASSWORD: medicine
        MYSQL_DATABASE: medicine
        MYSQL_ROOT_PASSWORD: medicine_root
